---
title: "Github 가입"
description: "Github 가입과 기초사용법에 대한 설명"
author: "BenKorea feat. ChatGPT"
date: "2024-10-25"
date-modified: last-modified
categories: [Github, sign up]
---

## Prologue

Git은 단순히 PC에서 개인 프로젝트의 버전을 관리하는 도구에 그치지 않고, 분산 환경에서 로컬(자신의 PC)과 원격 저장소를 연동하여 협업할 수 있도록 지원하는 분산형 버전 관리 시스템입니다. GitHub는 이러한 원격 저장소의 역할을 수행하는 대표적인 플랫폼으로, 오픈소스 협업을 위한 다양한 기능을 제공하지만 초보자 입장에서는 원격 저장소로 일단 이해해도 큰 문제는 없습니다.


## Github 가입
논리적으로는 Git 설치가 우선이지만, Github 가입시의 아이디와 이메일을 Git 설치단계에서 사용하는 것이 바람직한 면이 있고, Github의 아이디는 변경하기가 어렵고, Git 설정 시에 사용되는 아이디는 변경이 매우 쉽기 때문에 저자는 Github 가입을 먼저 설명하고자 합니다.
메인 사이트에서 가입 https://github.com/ 하시면 됩니다.

### 이메일 입력하기
Sign up하면 email을 입력해야 하는데 이미 등록된 이메일은 진행되지 않으므로 주의를 요합니다. 바로 다음 단계에 Git를 자신의 PC에 설치한 후 설정을 할 때, 커밋을 할 때, 어떠한 아이디와 이메일을 기록에 남길지 설정하게 되어 있는데, 이 때 저자는 Github에 가입하는 이메일과 일치하는 것이 좋다고 추천한다. (가입시의 이메일은 8자리 숫자로 구성된 launch code로 전송되어 오고, 이 값을 가입단계에서 입력을 해야 가입이 진행되는 등 실제적인 역할이 있지만 PC에서 커밋의 정보로 기록하는 것은 구별하기 위한 목적만 있기 때문에 작동하지 않는 메일이라고 하더라도 원칙적인 문제는 없습니다. 다만 커밋한 기록은 대체로 누군가가 보게되고 연락을 하고 싶다면 그 메일로 할 잠재적인 가능성 때문에 일치 시키는 것이 좋겠다고 저자는 생각합니다.

### Username과 Password 입력하기
위와 같은 Username을 바로 다음 단계의 Git 설치 후 설정에서와 일치시키는 것을 추천합니다.

### Launch code 입력하기
이메일로 전송된 8자리의 launch code를 입력해야 가입이 완료됩니다.


## Github 매뉴얼

설치 및 사용에 대해서는 아래의 공식자료를 활용하시길 추천합니다.

-   공식문서(<https://docs.github.com/ko>)는 한글로도 번역되어 있습니다.

-    공식 Training manual (<https://githubtraining.github.io/training-manual/#/>)도 있습니다.