project:
  type: website
  output-dir: ./docs
  

website:
  title: "RPythonStudy"
  navbar:
    logo: RPythonStudy_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: R_IDE.qmd
        text: R개발환경구축
      - href: R_manuscript.qmd
        text: R로 논문쓰기
      - href: preprocessing.qmd
        text: 데이터전처리
      - href: survival_analysis.qmd
        text: 생존분석


format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    toc: true
