project:
  type: website
  output-dir: .
  

website:
  title: "RPythonStudy Website"
  navbar:
    logo: RPythonStudy_logo.png
    left:
      - href: about.qmd
        text: about
      - href: R_IDE.qmd
        text: R 통합개발환경 구축
      - href: R_syntex.qmd
        text: R 문법
      - href: index.qmd
        text: 데이터전처리
      - href: survival_analysis.qmd
        text: 생존분석


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
