---
title: "의료빅데이터 분석을 위하여"
description: "이 웹사이틑 R과 Python을 이용하여 의료(빅)데이터를 분석하고자 하는 원내 연구자들에게 도움이 되고자 만들어졌습니다"
author: "BenKorea"
date: "April 12, 2024"
date-modified: last-modified
categories: [introduction]
---

## 웹사이트 사용법

### 상단메뉴

#### Blog
-   웹사이트의 모든 게시물을 목록으로 볼 수 있습니다.

#### 개발환경구축
- R과 Python의 설치만이 아니라 개발환경구축에 필요한 주요 설치들을 안내합니다.
- 아직은 미완이라 Python 설치와 관련된 안내만 있습니다.

#### R
- 개발환경구축 메뉴가 생기기 이전의 메뉴로 개발환경구축과 중복되는 내용이 있을 수 있으며, 미래에 통합될 예정입니다.

#### Python
- 개발환경구축 메뉴가 생기기 이전의 메뉴로 개발환경구축과 중복되는 내용이 있을 수 있으며, 미래에 통합될 예정입니다.

#### Quarto
-  Quarto는 기존의 R Markdown과 차별화된 기능을 제공하며, R, Python 등 다양한 프로그래밍 언어의 실행 결과를 통합 문서에 포함시킬 수 있습니다. 이를 통해 MS Word, PDF, LaTeX 등의 다양한 형식으로 문서를 출력할 수 있을 뿐만 아니라, 반응형 동적 웹페이지와 같은 디지털 출판 플랫폼으로서도 강력한 기능을 제공합니다. Quarto는 특히 재현 가능한 연구 및 데이터 중심의 보고서 작성을 위한 현대적인 도구로서, 다중 언어 환경에서의 동적 문서화와 프로그래밍 워크플로우의 통합을 지원합니다.
- 설치에 대한 부분은 미래에 통합될 예정입니다.

#### Statistics
- 연구회의 통계에 대한 강의를 게시

#### Quiz
- R에 대한 내용을 퀴즈를 진행하고 했습니다.
- 유지가 어려워 미래에는 삭제할 예정입니다.

#### Resources
- 연구회에 도움이 되는 medical (big) data resource들을 소개합니다.

#### Tools
- 연구회에 도움이 되는 open source program들을 소개합니다.

#### Concepts
- 코딩 시 알아야할 개념들에 대한 설명입니다.


### 날짜의 의미
-   각 웹페이지는 두 가지 날짜가 있으며 이 웹사이트에서는 구별되어 사용되고 있습니다.
    - 공개(PUBLISHED)는 최초작성일에 해당하는 개념입니다.
        -   블로그에서 정렬방법을 날짜-날짜(오름차순), 날짜-날짜(내림차순)을 선택했을 때 정렬기준으로 사용됩니다.
    - MODIFIED는 최종수정일에 해당하는 개념입니다.
        -   블로그에서 Default로 정렬할 때 기준으로 사용됩니다.
        -   Default로 정렬할 때 내부적으로 MODIFIED 날짜의 최신순으로 되지만, 정렬된 페이지목록에서 각 페이지의 왼쪽의 보여지는 날짜는 MODIFIED가 아닌 공개(PUBLISHED)를 보여줍니다. 이로인해 Defalut 정렬에서 각 페이지의 날짜와 정렬이 맞지 않는 것처럼 착각될 수 있으므로 주의를 요합니다. 


## **의료데이터 분석연구에서 R과 Python의 필요성**

의학연구를 통계프로그램으로 SPSS 또는 MedCalc가 많이 사용됩니다. 그러나 병원에서만 이용할 수 있고 분석과정을 자동화할 수 없습니다.

이에 비해 오픈소스 통계언어인 R은 간단한 프로그램밍을 통해 분석과정을 자동화할 수 있고, 시각화에 뛰어나고 분석결과를 의학논문 작성까지 연계할 수 있고 웹에 게시하는 것도 용이합니다.

Python은 범용적인 오픈소스 프로그램밍 언어이며 기계학습과 딥러닝에 강점이 있고 R과의 연계도 뛰어납니다. 공통적으로 둘다 빅데이터 분석이 가능하다는 장점도 있습니다.

특정 저널에서는 재현가능한 연구를 위해 R Markdown 형식으로 투고를 받기도 합니다. 따라서 임상연구를 포함해서 연구자들에게 장점이 맞은 오픈소스툴입니다.

## R과 Python을 이용한 의료데이터 분석연구회 (RPythonStudy Group)

R과 Python을 이용하여 의료데이터를 분석하고자 하는 원내 연구자들에게 도움이 되고자 이 사이트를 만들었습니다.


```{r eval=FALSE, filename="e-mail"}
r.python.study@gmail.com
```

