---
title: "파이썬 설치 - RPython 강의록"
description: "윈도우와 mac에서 Power Shell, Scoop, Git, Python 설치"
author: "LeeBC"
date: "2025-11-24"
date-modified: last-modified
categories:
  - introduction
---


# Chrome Browser에서 md 파일 보기 - Markdown Reader extension 
- Markdown reader extension 설치 
- chrome brower 주소창에. 
```{r chrome_extension, eval=FALSE, filename="chrome brower"}
chrome://extensions
``` 
- allow local file URL access 

# Windows 에서 파이썬 설치 

## Powershell 업그레이드, 정리. 
- 설치
```powershell
winget install --id Microsoft.Powershell --source winget
```
- 실행  : `pwsh.exe`
- Powershell 7 의 위치  `C:\Program Files\PowerShell\7\pwsh.exe`
- 최신 버전 파워셀 설치 명령어 
```powershell
iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
```
- restrict 제거 
```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser  
```

## Scoop 설치  
-  Powershell  일반 모드에서 실행해야 함. 
```powershell
Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
```
```Powershell
irm get.scoop.sh | iex
```
- Git 설치 :  Scoop 을 이용해서  설치 
```powershell
scoop install main/git  
```
## Scoop 을 이용해서 파이썬 설치 
- Python 설치 
```Powershell
scoop install versions/python39  
scoop install versions/python312
```
- Scoop 에 설치된 패키지 리스트 보기 
```powershell
scoop list 
```
- Switch to specific python
```powershell
scoop reset python312
```

## Project folder 만들고 Virtual Environment  설정 , 실행.  
- 현재 파이썬 버전 확인
```powershell
python -V 
```
	- `V`  가 대문자 

- 프로젝트 폴더로 이동
```powershell
cd  Py_Project
```
	- cd : change directory

- 가상환경 설치
```powershell
python -m venv .venv 
```

- 가상환경 활성화 
```powershell
.\.venv\Scripts\Activate.ps1
```

- 파이썬 실행 파일이 어디있나? 
```powershell
where.exe python 
```

```powershell
C:\Users\bclee\Codes\PyLib\.venv\Scripts\python.exe  (가상환경 파이썬)
C:\Users\bclee\scoop\apps\python311\current\python.exe (Scoop 에서 현재 설정된 파이썬 )
C:\Users\bclee\AppData\Local\Microsoft\WindowsApps\python.exe (윈도우즈 패키지로 설치한 파이썬)
```


- 가상환경 끄기 
```powershell
deactivate
```

# Mac 에서 파이썬 설치

## brew 설치
- install git  (if needed)
```zsh
apt update 
```
```zsh
apt install git
```

- install curl (if needed)
```zsh
apt install curl 
```

- brew 설치 with curl
```zsh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
- brew 를 path에 넣어주기 
```zsh
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/charlie/.zprofile
```
	- (User 이름이 charlie 인 경우)

## pyenv 설치

```zsh
brew install pyenv
```

## pyenv 을 이용해서 파이썬 설치 
- 현재 사용  가능한 파이썬 버전 보기 (3.9 버전)
```zsh
pyenv install --list | grep " 3\.9\.." 
```
- 특정버전 설치
```zsh
pyenv install 3.11
```
- 현재 설치된 버전 보기
```zsh
pyenv versions 
```
- 사용할 버전 지정
```zsh
pyenv global 3.11.9
```

## Project folder 만들고 Virtual Environment  설정 , 실행.  (윈도우와 거의 동일, 단, activate 명령만 다름)

- 현재 파이썬 버전 확인
```zsh
python -V 
```
	- `V`  가 대문자 

- 프로젝트 폴더로 이동
```zsh
cd  Py_Project
```
	- cd : change directory

- 가상환경 설치
```zsh
python -m venv .venv 
```

- 가상환경 활성화 (윈도우와 다른 점)
```zsh
source ./.venv/bin/activate
```

- 파이썬 실행 파일이 어디있나? (윈도우와 다른점)
```zsh
where python 
```

```zsh
C:\Users\bclee\Codes\PyLib\.venv\Scripts\python.exe  (가상환경 파이썬)
C:\Users\bclee\scoop\apps\python311\current\python.exe (Scoop 에서 현재 설정된 파이썬 )
C:\Users\bclee\AppData\Local\Microsoft\WindowsApps\python.exe (윈도우즈 패키지로 설치한 파이썬)
```


- 가상환경 끄기 
```zsh
deactivate
```

